### PR TITLE
Added disable button style

### LINKED ISSUE #71: Need styling for disabled buttons.

### PR DESCRIPTION
**Pull request by UsamaSaleem14**
Changes in this PR:

Added a disable button style for the button when it is in loading state. When the user click submit the button will turn into a loading button with no click events on it.

image

### CODE REVIEW

**Comment by TBomberman** [comment]
Please describe the changes here next time.

**Comment by UsamaSaleem14** [comment]
> Please describe the changes here next time.

Done

**Comment by TBomberman** [comment]
Please check if there are any disabled buttons that are shown without loading. This issue was meant for buttons that are shown but are not enabled.

**Comment by UsamaSaleem14** [comment]
> Please check if there are any disabled buttons that are shown without loading. This issue was meant for buttons that are shown but are not enabled.

All the buttons are only shown whenever necessary, otherwise they are not shown.

Moreover, should I remove the current disable button styling that I did for submit buttons?

**Comment by TBomberman** [comment]
Ok, I see, if it's just to add the style, then can you put it into the CommonStyles? No other changes are required I think.

**Pull request closed without merging**
